project_name: tfplugindocs
builds:
- main: ./cmd/tfplugindocs
  env:
  - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  ldflags:
  - '-s -w -X github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs/build.version={{.Version}} -X github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs/build.commit={{.Commit}}'
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  binary: '{{ .ProjectName }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
milestones:
  - close: true
release:
